# Generated by Django 3.1.6 on 2021-05-05 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_auto_20210501_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonhanQuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200)),
                ('quest_name', models.CharField(max_length=100)),
                ('hunter_name', models.CharField(max_length=100)),
                ('room_id', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('master_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
