# Generated by Django 3.1.6 on 2021-03-06 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='e_sport_detail',
            field=models.CharField(blank=True, choices=[('10', 'FORTNITE'), ('20', 'PUBG'), ('30', 'APEX'), ('40', 'MINECRAFT'), ('50', 'League of Legends'), ('60', 'その他')], max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='hobby_detail',
            field=models.CharField(blank=True, choices=[('10', '読書会'), ('20', '懇親会'), ('30', '朝活'), ('40', 'その他')], max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='work_detail',
            field=models.CharField(blank=True, choices=[('10', 'セミナー'), ('20', '意見交換会'), ('30', '名刺交換会'), ('40', '学生向け'), ('50', 'その他')], max_length=100),
        ),
    ]
