# Generated by Django 3.1.6 on 2021-03-06 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210306_1341'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Check',
        ),
    ]
