# Generated by Django 3.1.6 on 2021-03-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_delete_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='sns_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
