# Generated by Django 3.1.6 on 2021-03-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210307_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='sns_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
