# Generated by Django 3.1.6 on 2021-03-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20210307_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
