# Generated by Django 3.1.6 on 2021-03-03 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_twitter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Twitter_profile_image_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
