# Generated by Django 3.1.6 on 2021-03-03 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_twitter_profile_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Twitter_profile_image',
            new_name='profile_image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Twitter_profile_image_url',
        ),
    ]
